# Setup
title:               'FV Utilites'
tagline:             'Functional Verification Utilities'
description:         ''
url:                 ''
baseurl:             ''
#permalink:           pretty

exclude:
    - packages

# About/contact
author:
  name:              Matthew Ballance
  url:               http://fvutils.github.io
  email:             matt.ballance@gmail.com

rooturl: http://fvutils.github.io
  
github:
  repo: http://github.com/fvutils

# Custom vars
version:             1.0.0
google_analytics_id: G-B75HY0XCL2

copyright:             Â© <!--copyyears--> Matthew Ballance; All rights reserved.
